# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
